overrides:
- files: "EvoMp/**/*.ts"
  options:
    printWidth: 200
    semi: false
    singleQuote: true
    trailingComma: "none"
    useTabs: false
    tabWidth: 2
    bracketSpacing: false
    arrowParens: "always"
