#notify:
#  webhooks:
# A list of hook hashes, containing the URL field (Deprecaded. See CircleCi proyect Settings. (WebHook, Slack)
#- url: https://skyhook.glitch.me/api/webhooks/419513949084712960/J5ecD0bCr976sG7UVzva5wE7lylxbId924kstfhDUPkEXczkVxPNkYuJmcMk35o4y31R/circleci
version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: kola50011/evomp
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      # Server side
      #- run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | tee /etc/apt/sources.list.d/mono-official.list; apt-get update;
      #- run: apt-get update; apt-get install mono-devel nuget zip -y
      - run: nuget setapikey acaa0928-8a4a-4d36-82a3-14b3ab8452fc -source https://www.myget.org/F/gt5mp/api/v2; nuget sources add -Name "grandtheftmultiplayer.api" -source "https://www.myget.org/F/gt5mp/api/v2" -User XXXX -pass XXXXXXX -ConfigFile /root/.config/NuGet/NuGet.Config;  
      - run:
          path: /temp/EvoMp
          command: nuget restore EvoMp.sln -NoCache -ConfigFile /root/.config/NuGet/NuGet.Config   
      - run:
          path: /temp/EvoMp
          command: msbuild EvoMp.sln /p:TargetFrameworkVersion=v4.6.2 /p:Configuration=Linux-Release
      # Client side
      #- run: curl -sL https://deb.nodesource.com/setup_8.x | bash - ; apt-get install -y nodejs; #NodeJs
      - run: apt-get install apt-transport-https -y; curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -""; echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list; #apt-get update && apt-get install yarn; #Yarn
      - run: 
          path: /temp
          command: yarn install
      - run:
          path: /temp
          command: yarn build
      # Start Server in onlyCopy
      - run:
          path: /temp/GTMP_Server
          command: mono GrandTheftMultiplayer.Server.exe -onlyCopy true
      #zip and archive
      - run:
          path: /temp
          command: zip -r GTMP_Server.zip GTMP_Server
      - store_artifacts:
          path: /temp/GTMP_Server.zip
