version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:2-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get install mono-xbuild
      - run:
          path: /temp/EvoMp
          command: dotnet restore EvoMp.sln --configfile /EvoMp/NuGet.Config
      - run:
          path: /temp/EvoMp
          command: xbuild EvoMp.sln
