using EvoMp.Module.ClientWrapper.Enums;
using EvoMp.Module.VehicleUtils.Server.Enums;
using GrandTheftMultiplayer.Server.Constant;
using GrandTheftMultiplayer.Server.Elements;
using GrandTheftMultiplayer.Shared;
using GrandTheftMultiplayer.Shared.Gta.World;
using GrandTheftMultiplayer.Shared.Math;

namespace EvoMp.Module.ClientWrapper.Server
{
    public interface ISetFunctions
    {
        void SetAudioTime(Client sender, int seconds);
        void SetBlipColor(Client sender, NetHandle blip, int color);
        void SetBlipName(Client sender, NetHandle blip, string name);
        void SetBlipPosition(Client sender, NetHandle blip, Vector3 position);
        void SetBlipScale(Client sender, NetHandle blip, double scale);
        void SetBlipShortRange(Client sender, NetHandle blip, bool shortRange);
        void SetBlipSprite(Client sender, NetHandle blip, int sprite);
        void SetBlipTransparency(Client sender, NetHandle blip, int alpha);
        void SetCanOpenChat(Client sender, bool show);
        void SetChatVisible(Client sender, bool display);
        void SetDisplayWastedShard(Client sender, bool show);
        void SetEntityCollissionless(Client sender, NetHandle entity, bool status);
        void SetEntityDimension(Client sender, NetHandle entity, int dimension);
        void SetEntityInvincible(Client sender, NetHandle entity, bool invincible);
        void SetEntityPosition(Client sender, NetHandle entity, Vector3 position);
        void SetEntityPositionFrozen(Client sender, NetHandle entity, bool frozen);
        void SetEntityRotation(Client sender, NetHandle entity, Vector3 rotation);
        void SetEntityTransparency(Client sender, NetHandle entity, int alpha);
        void SetEntityVelocity(Client sender, NetHandle entity, Vector3 velocity);
        void SetGameplayCameraActive(Client sender);
        void SetGameVolume(Client sender, int vol);
        void SetHudVisible(Client sender, bool visible);
        void SetMarkerColor(Client sender, NetHandle marker, int alpha, int red, int green, int blue);
        void SetMarkerDirection(Client sender, NetHandle marker, Vector3 dir);
        void SetMarkerScale(Client sender, NetHandle marker, Vector3 scale);
        void SetMarkerType(Client sender, NetHandle marker, MarkerType type);
        void SetPlayerAccessory(Client sender, NetHandle player, int slot, int drawable, int texture);
        void SetPlayerArmor(Client sender, int armor);
        void SetPlayerClothes(Client sender, NetHandle player, int slot, int drawable, int texture);
        void SetPlayerDefaultClothes(Client sender);
        void SetPlayerHealth(Client sender, double health);
        void SetPlayerIntoVehicle(Client sender, NetHandle vehicle, int seat);
        void SetPlayerInvincible(Client sender, bool invinc);
        void SetPlayerNametag(Client sender, NetHandle player, string text);
        void SetPlayerNametagColor(Client sender, NetHandle player, int red, int green, int blue);
        void SetPlayerNametagVisible(Client sender, NetHandle player, bool show);
        void SetPlayerSkin(Client sender, int model);
        void SetPlayerTeam(Client sender, int team);
        void SetPlayerWantedLevel(Client sender, int wantedLevel);
        void SetPlayerWeaponTint(Client sender, WeaponHash weapon, WeaponTint tint);
        void SetSetting(Client sender, string name, dynamic value);
        void SetTextLabelColor(Client sender, NetHandle textLabel, int alpha, int red, int green, int blue);
        void SetTextLabelSeethrough(Client sender, NetHandle handle, bool seethrough);
        void SetTextLabelText(Client sender, NetHandle label, string text);
        void SetTime(Client sender, int hours, int minutes);
        void SetUiColor(Client sender, int red, int green, int blue);
        void SetVehicleBulletproofTyres(Client sender, NetHandle vehicle, bool bulletproof);
        void SetVehicleCustomPrimaryColor(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleCustomSecondaryColor(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleDashboardColor(Client sender, NetHandle vehicle, int type);
        void SetVehicleDoorState(Client sender, NetHandle vehicle, DoorState door, bool open);
        void SetVehicleEnginePowerMultiplier(Client sender, NetHandle vehicle, double mult);
        void SetVehicleEngineStatus(Client sender, NetHandle vehicle, bool turnedOn);
        void SetVehicleEngineTorqueMultiplier(Client sender, NetHandle vehicle, double mult);
        void SetVehicleExtra(Client sender, NetHandle vehicle, int slot, bool enabled);
        void SetVehicleLivery(Client sender, NetHandle vehicle, double livery);
        void SetVehicleLocked(Client sender, NetHandle vehicle, bool locked);
        void SetVehicleMod(Client sender, NetHandle vehicle, int slot, int modType);
        void SetVehicleModColor1(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleModColor2(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleNeonColor(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleNeonState(Client sender, NetHandle vehicle, int slot, bool turnedOn);
        void SetVehicleNumberPlate(Client sender, NetHandle vehicle, string plate);
        void SetVehicleNumberPlateStyle(Client sender, NetHandle vehicle, int style);
        void SetVehiclePearlescentColor(Client sender, NetHandle vehicle, int color);
        void SetVehiclePrimaryColor(Client sender, NetHandle vehicle, int color);
        void SetVehicleSecondaryColor(Client sender, NetHandle vehicle, int color);
        void SetVehicleSpecialLightStatus(Client sender, NetHandle vehicle, bool status);
        void SetVehicleTrimColor(Client sender, NetHandle vehicle, int type);
        void SetVehicleTyreSmokeColor(Client sender, NetHandle vehicle, int red, int green, int blue);
        void SetVehicleWheelColor(Client sender, NetHandle vehicle, int color);
        void SetVehicleWheelType(Client sender, NetHandle vehicle, int type);
        void SetVehicleWindowTint(Client sender, NetHandle vehicle, int type);
        void SetWaypoint(Client sender, double x, double y);
        void SetWeather(Client sender, GrandTheftMultiplayer.Shared.Gta.World.Weather weather);
    }
}
